//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NKSApp.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NKSEntitie : DbContext
    {
        private static NKSEntitie _Context;
        public NKSEntitie()
            : base("name=NKSEntitie")
        {
        }

        public static NKSEntitie GetContext()
        {
            if (_Context == null)
                _Context = new NKSEntitie();
            return _Context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Executor> Executor { get; set; }
        public virtual DbSet<Operator> Operator { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Shutdown> Shutdown { get; set; }
        public virtual DbSet<Source> Source { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
    }
}
