//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NKSApp.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public string ContentN { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string Applicant { get; set; }
        public Nullable<int> ExecutorID { get; set; }
        public string Adress { get; set; }
        public string СonvenientTime { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Executor Executor { get; set; }
        public virtual Source Source { get; set; }
        public virtual Status Status { get; set; }
        public virtual Type Type { get; set; }
    }
}
